### ISSUE TITLE
Cant compile with default doorbell.yaml

### ISSUE THREAD

**Issue by 000al000** [pauln/esphome-linp-doorbell-g04#1]
I try compile  default doorbell.yaml with esphome 2022.1.1

Error

      variables:
        tune: int
        volume: int
        mode: int
      then:  [source doorbell.yaml:30]
        - [source doorbell.yaml:30]

          Unable to find action with the name 'remote_transmitter.transmit_szy8039b'.
          remote_transmitter.transmit_szy8039b:  [source doorbell.yaml:31]

In gl03 in yaml was section external_componets, may be this should have it too?

**Comment by pauln** [comment]
Sorry - yes, that section is needed.  I developed this as a local custom component, and forgot to add this section when preparing it for release as an external component.  I've just pushed a commit which adds the missing `external_components` section.
