### ISSUE TITLE
Contacts for flash mode

### ISSUE THREAD

**Issue by nemoyar** [pauln/esphome-linp-doorbell-g04#2]
I can not understand which contacts to close for transfer to flash in the new version. How below?
The description says "In order to boot the ESP32 into flash mode (so that you can write ESPHome to it), you'll need to pull the two pins closest the bottom right corner of the ESP32 module to ground"
![20220124_134832](https://user-images.githubusercontent.com/16333431/150769987-11c8bfa4-4ec3-43cf-af45-94a823f43384.jpg)

**Comment by nemoyar** [comment]
Connected like this, but the firmware does not go. There is usb-to-TTL in linux, but the firmware is not uploaded. Maybe you can't take 3.3V from a USB-to-TTL adapter? 3,3V is on the doorbell board
![20220124_204527](https://user-images.githubusercontent.com/16333431/150836576-22599256-50de-49c8-9b6a-9616598a7d24.jpg)
![20220124_204548](https://user-images.githubusercontent.com/16333431/150836578-107c8463-6c0a-4777-9d40-30f3f1267ec2.jpg)
![2](https://user-images.githubusercontent.com/16333431/150841272-65cf61f5-2c38-4d25-8d9b-a91c0fe4b734.JPG)

**Comment by pauln** [comment]
USB-to-TTL adapters often only provide a small amount of current on their 3.3v pin - not enough to power up and flash an ESP32 - so an external supply is recommended.  That said, your screenshot doesn't show it getting as far as flashing.  Have you successfully flashed other ESP devices from that Raspberry Pi?

**Comment by nagyrobi** [comment]
The USB-TTL adapter shown in the photo should be strong enough, I have the same type, it's very good.

**Comment by nemoyar** [comment]
> USB-to-TTL adapters often only provide a small amount of current on their 3.3v pin - not enough to power up and flash an ESP32 - so an external supply is recommended. That said, your screenshot doesn't show it getting as far as flashing. Have you successfully flashed other ESP devices from that Raspberry Pi?

no, first time on this.
But if command "esphome logs ~/esphome-linp-doorbell-g04-main/doorbell.yaml" and after that connect 3.3V to bell getting it:
![image](https://user-images.githubusercontent.com/16333431/150848107-9318eba3-3e46-4afb-af79-d3faf3956364.png)

**Comment by nemoyar** [comment]
> not enough to power up and flash an ESP32 - so an external supply is recommended

how much should be and how to check (on which contacts)?

**Comment by nemoyar** [comment]
Precisely close contacts IO0 and IO2 to GND?
![22](https://user-images.githubusercontent.com/16333431/150854694-833891b1-055f-46f4-816b-e22666c09912.JPG)

**Comment by pauln** [comment]
> But if command "esphome logs ~/esphome-linp-doorbell-g04-main/doorbell.yaml" and after that connect 3.3V to bell getting it:

This looks like you're successfully putting the ESP32 into flashing mode (`waiting for download`).

Going back to my earlier comment:
> That said, your screenshot doesn't show it getting as far as flashing

I don't have a Raspberry Pi myself, so I haven't kept up on what's involved in compiling for ESP32 on a Pi - but as far as I'm aware, there's no "official" xtensa toolchain available for the Pi.  You might need to [build your own](https://rawats.medium.com/using-raspberry-pi-for-embedded-systems-development-part-3-2485d1522aba#e69c) or try a precompiled version such as https://github.com/koendv/xtensa-esp32-elf-raspberrypi (those are both just results of a quick Google search; as such I can't recommend either of them - I'm just sharing them as an example.  Please do your own research).

**Comment by nemoyar** [comment]
> I don't have a Raspberry Pi myself

where do you recommend installing esphome for firmware?

**Comment by pauln** [comment]
I run ESPHome on my laptop, which is running Ubuntu - but the website has [instructions for Windows and Mac as well](https://esphome.io/guides/installing_esphome.html), or if you have Docker set up, you can try [pulling the ESPHome image](https://esphome.io/guides/getting_started_command_line.html#installation).  It sounds like the ARM64 docker image should work on the Pi, so if you really want to run ESPHome on the Pi, that might be the easiest way to get it working.

**Comment by nemoyar** [comment]
I'm running in Ubuntu and got result. This is correct?
![1](https://user-images.githubusercontent.com/16333431/151131887-5bf98adb-5bcc-41d3-90f8-6961144bf0d8.png)

**Comment by pauln** [comment]
Yes, that looks correct.  If you remove the short to ground on the corner pins and then power cycle the doorbell, it should boot into ESPHome (and `esphome logs doorbell.yaml` should show be able to connect and show you the logs, as long as you enabled logging in your config).

**Comment by nemoyar** [comment]
I opened the contacts, the doorbell blinks orange, in the terminal it writes about the full buffer
![22](https://user-images.githubusercontent.com/16333431/151139336-98cff8eb-a695-4fce-9954-7863c4dea137.png)
When press button on doorbell in log message:
![4](https://user-images.githubusercontent.com/16333431/151140151-bdcbe9f8-f284-40f4-8873-6ea200638c8c.png)

**Comment by nemoyar** [comment]
I got an object in HA, switches work when I press the block buttons, but there is no call when I press the call button. In which sensor should the event go when the call button is pressed? Sensor A or B?
![image](https://user-images.githubusercontent.com/16333431/151141618-3c51c559-d735-444c-b8f3-144b0fe4097d.png)

**Comment by pauln** [comment]
The `RMT RX BUFFER FULL` messages suggest that there might be a lot of RF noise (or other transmissions) in your area around 433MHz.  I haven't seen that myself, so I'm not sure whether you'll still be able to reliably receive the call button transmissions in that state.

Do you see log messages like the following when you press the call button(s)?

`[remote.linptech_g6l:068]: Received Linptech G6L: address=0x123456`

If so, use that `address` value to configure your `remote_receiver` binary sensor(s), recompile/reflash the ESP32 with the updated config, and you should start receiving events in Home Assistant.  If you don't see these log lines, try adjusting the [remote receiver config](https://esphome.io/components/remote_receiver.html#configuration-variables) - increasing `memory_blocks` above the default (3) might help, or you might be able to increase the `filter` time slightly (not much, though, as the transmissions use quite short pulses) to cut out more of the noise.

**Comment by nemoyar** [comment]
> Do you see log messages like the following when you press the call button(s)?

When I click the buttons on base  the event in the log look like this
![image](https://user-images.githubusercontent.com/16333431/151146617-5080a375-eaab-426e-879a-6ed7ba0321fc.png)

Update: I logged the Received "Linptech G6L: address=" entry when I clicked the button!
Thank You very much!
