### ISSUE TITLE
Device is not responding when updated to firmware 2024.10.0

### ISSUE THREAD

**Issue by czar-labs** [pauln/esphome-linp-doorbell-g04#9]
I did an update the ESPHome on HA to 2024.10.0
When it finished, the notification for firmware update for doorbell is appeared.
When I update the firmware of doorbell to 2024.10.0, there is a log indicated below 
`esp home [D][esp-idf:000]: E (6134) system_api: Base MAC address from BLK3 of EFUSE version error, version = 70`

Then the API to HA is disconnected and the device is not responding

Have you experienced the same?

I am relatively new on this ESP things, it seems the problem is related to the MAC address

**Comment by pauln** [comment]
@czar-labs It looks as though [ESPHome 2024.10 now tries to use the MAC address burnt into the eFuse blocks](https://esphome.io/changelog/2024.10.0.html#esp32-advanced-mac-address-configuration) - so the error you're getting seems to suggest that these chips don't just have a bad MAC address CRC in eFuse, but also a bad MAC address (or, more likely, those eFuse blocks are used for something else on these chips).

Can you please try adding `ignore_efuse_custom_mac: True` to the `esp32 -> framework -> advanced` config block, along with (either above or below, at the same indentation level as) the `ignore_efuse_mac_crc: True` that's already there?  If you're not able to do an OTA update when it's in this state, you might need to flash it via serial (as you did to get ESPHome onto it initially).

**Comment by czar-labs** [comment]
> ignore_efuse_custom_mac: True

Many thanks for your reply
I confirm it works great

Thank you!

**Comment by pauln** [comment]
Thanks for confirming.  I've added it to the sample config (along with a comment and a note in the readme).
